feat: Layout API SDK addition
novuhq/novu-rust pull request #35
Opened 2023-10-18 17:20 UTC by srikanth597

2023-10-19 12:22 UTC, kymppi requested changes

2023-10-19 12:22 UTC, kymppi commented on src/changes.rs
> -fn generate_query_string(params: &HashMap<&str, Option<impl ToString>>) -> String {
Could this function be moved to another file? Maybe something like `utils`.

2023-10-19 15:05 UTC, srikanth597 commented on src/changes.rs
> -fn generate_query_string(params: &HashMap<&str, Option<impl ToString>>) -> String {
moved it to utils

2023-10-19 15:06 UTC, srikanth597 commented
@kymppi now we should be good

2023-10-19 15:34 UTC, kymppi requested changes
Oops sorry for having to deny this. The CI (tests) seem to report some problems so please fix those 🙂

2023-10-19 18:45 UTC, srikanth597 commented
now we are good with the checks, please review & merge it.

2023-10-19 18:45 UTC, srikanth597 commented
@kymppi also requesting you to add hactoberfest labels

2023-10-22 17:34 UTC, kymppi approved these changes

2023-10-22 17:34 UTC, merged